on:
  push:
    branches:
      - main
      - development
      - suz-testthat-brainstorm2
  pull_request:
    branches:
      - main
      - development

name: test-CBMutils-install

jobs:
  test-CBMutils-install:
    if: "!contains(github.event.commits[0].message, '[skip-ci]')"
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'devel'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,  r: 'devel'}
          - {os: ubuntu-latest,  r: 'release'}
          - {os: macOS-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_AUTH: ${{ secrets.GOOGLE_AUTH }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - uses: actions/checkout@v4

      - name: Install fontconfig (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt -y install libfontconfig1-dev
          sudo apt-get install libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev
        shell: bash

      - uses: PredictiveEcology/actions/install-spatial-deps@v0.2

      - uses: r-lib/actions/setup-r@v2
        with:
          extra-repositories: 'https://predictiveecology.r-universe.dev/'
          Ncpus: 2
          r-version: ${{ matrix.config.r }}
          use-public-rspm: false

      - name: Install R package 'BH' (macOS)
        if: runner.os == 'macOS'
        run: |
          install.packages("BH")
        shell: Rscript {0}

      - name: Install CBMutils
        run: |
          install.packages("devtools")
          devtools::install_github("PredictiveEcology/CBMutils@development", dependencies = TRUE)
        shell: Rscript {0}

